spring:
  activemq:
    broker-url: tcp://localhost:61616
    user:
    password:
    #默认包名安全 （支持序列化反序列化）
    packages:
      trust-all: true
    pool:
      enabled: true
      max-connections: 10
  #支持topic模式
  jms:
    pub-sub-domain: true