spring:
  profiles:
    #    active: "tut1,sender,receiver"
    active: "remote,tut8,sender,receiver"
    #    active: "tut2,sender,receiver"
  #    active: "tut3,sender,receiver"
  #    active: "tut4,routing,sender,receiver"

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000
server:
  port: 8080


